import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import { Providers } from "../providers/providers";
import { Navbar } from "@/common/navbar/Navbar";
import { Footer } from "@/common/footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Reservation App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <main className="flex min-h-screen w-full flex-col pl-20 pr-20 bg-main">
          <Providers>
            <Navbar />
            <div className="minh-full-minus-nav h-full w-full">{children}</div>
            <Footer />
          </Providers>
        </main>
      </body>
    </html>
  );
}
