version: '3'
services:
  # frontend:
  #   image: next-nginx:dev
  #   build:
  #     context: ./frontend
  #   depends_on:
  #     - backend
  #   container_name: frontend
  #   ports:
  #     # - "3000:3000"
  #     # - "443:443"
  #     - "3000:80"
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    # volumes:
    #     - .:/app
    #     - /app/node_modules
    #     - /app/.next
    ports:
      - "3000:3000"

  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8090:8090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: 'postgres:latest'
    container_name: db
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres


