version: '3'
services:
  frontend:
    build: frontend/.
    depends_on:
      - backend
    container_name: frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt/archive/arcziweb.com:/etc/nginx/ssl

  backend:
    build: backend/.
    container_name: backend
    ports:
      - "8090:8090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: 'postgres:latest'
    container_name: db
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres


